/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Db

/-!
# The declarative migration example

Two hand-written migrations and the demo that applies them. Backend-neutral on purpose: the point
of declaring a migration in Lean is that the same migration runs on either backend, so the demo is
polymorphic in the monad and both suites run the same one.

The tables are called `mig_author` and `mig_book` rather than `author` and `book` so that the demo
does not collide with the model tables the other examples `autoUpdate` into the same database.
-/

namespace MigrationExample

open Db.Migration

/-! ### The schema the migrations build

Written out as a `Table`, rather than generated by `@[model]`, because the point here is the
constraints: `mig_author` has a primary key for `mig_book`'s foreign key to reference. -/

inductive MigAuthorIndex where
  | name
  | age
  deriving DecidableEq, Hashable, Repr, Enum

instance : ToString MigAuthorIndex where
  toString
    | .name => "name"
    | .age => "age"

instance : FromString MigAuthorIndex where
  fromString
    | "name" => some .name
    | "age" => some .age
    | _ => none

instance : Indexing MigAuthorIndex where

def migAuthorTable : Table where
  Index := MigAuthorIndex
  columns
    | .name => { type := .varchar 100, nullable := false }
    | .age => { type := .int, nullable := false }
  primaryKey := [.name]

inductive MigBookIndex where
  | title
  | author
  | year
  | note
  deriving DecidableEq, Hashable, Repr, Enum

instance : ToString MigBookIndex where
  toString
    | .title => "title"
    | .author => "author"
    | .year => "year"
    | .note => "note"

instance : FromString MigBookIndex where
  fromString
    | "title" => some .title
    | "author" => some .author
    | "year" => some .year
    | "note" => some .note
    | _ => none

instance : Indexing MigBookIndex where

/-- `note` is the column the second migration adds, so the schema declared here is the schema
*after* both migrations. -/
def migBookTable : Table where
  Index := MigBookIndex
  columns
    | .title => { type := .varchar 200, nullable := false }
    | .author => { type := .varchar 100, nullable := false }
    | .year => { type := .int, nullable := true }
    | .note => { type := .text, nullable := true }
  primaryKey := [.title]
  foreignKeys :=
    [{ columns := [.author]
       foreignTable := "mig_author"
       foreignColumns := ["name"]
       onDelete := .cascade }]

inductive MigDbIndex where
  | author
  | book
  deriving DecidableEq, Hashable, Repr, Enum

instance : ToString MigDbIndex where
  toString
    | .author => "mig_author"
    | .book => "mig_book"

instance : FromString MigDbIndex where
  fromString
    | "mig_author" => some .author
    | "mig_book" => some .book
    | _ => none

instance : Indexing MigDbIndex where

def migDb : Database where
  Index := MigDbIndex
  tables
    | .author => migAuthorTable
    | .book => migBookTable

/-- The index the second migration leaves behind. -/
def yearIndex : TableIndex String :=
  { name := "idx_mig_book_year", keys := [{ column := "year", direction := .desc }] }

/-- The schema the code declares: the two tables and the one index. This is what
`makemigrations` diffs the migrations against. -/
def migSchema : DatabaseRecipe :=
  migDb.recipe.withIndexes "mig_book" [yearIndex]

/-! ### The migrations -/

/-- The first migration: the two tables as they were before `note` existed, and an index on the
column the books were looked up by at the time. -/
def migration0001 : Migration where
  name := "0001_initial"
  steps :=
    [ .createTable "mig_author"
        { columns := .ofList
            [("name", { type := .varchar 100, nullable := false }),
             ("age", { type := .int, nullable := false })]
          primaryKey := ["name"] },
      -- After `mig_author`: a `CREATE TABLE` carrying `REFERENCES` fails unless its target exists.
      .createTable "mig_book"
        { columns := .ofList
            [("title", { type := .varchar 200, nullable := false }),
             ("author", { type := .varchar 100, nullable := false }),
             ("year", { type := .int, nullable := true })]
          primaryKey := ["title"]
          foreignKeys :=
            [{ columns := ["author"], foreignTable := "mig_author",
               foreignColumns := ["name"], onDelete := .cascade }] },
      .createIndex "mig_book"
        { name := "idx_mig_book_author", keys := [{ column := "author" }] } ]

/-- The second migration: a new column, the rows that go in it, a fix-up in raw SQL, and the index
that replaces the one the first migration created.

The `run` step is the data migration: ordinary typed inserts, written once and running on either
backend. It comes after the `addColumn` because it inserts through `migDb`, which declares the
column the `addColumn` adds. -/
def migration0002 : Migration where
  name := "0002_data"
  steps :=
    [ .addColumn "mig_book" "note" { type := .text, nullable := true },
      .run do
        DBMonad.insert (d := migDb) (name := MigDbIndex.author)
          { value
              | .name => some (v"Ada")
              | .age => some (36 : Int) }
        DBMonad.insert (d := migDb) (name := MigDbIndex.author)
          { value
              | .name => some (v"Bram")
              | .age => some (50 : Int) }
        DBMonad.insert (d := migDb) (name := MigDbIndex.book)
          { value
              | .title => some (v"Persuasion")
              | .author => some (v"Ada")
              | .year => some (some (1817 : Int))
              | .note => none }
        DBMonad.insert (d := migDb) (name := MigDbIndex.book)
          { value
              | .title => some (v"Dracula")
              | .author => some (v"Bram")
              | .year => some (some (1897 : Int))
              | .note => none },
      -- The escape hatch: a data fix-up the operation language has no word for. The same text on
      -- both backends, so `Step.sql` rather than `Step.sqlByDialect`.
      .sql "UPDATE mig_book SET note = 'classic' WHERE year < 1850",
      .dropIndex "mig_book" "idx_mig_book_author",
      .createIndex "mig_book" yearIndex ]

/-- Every migration this example declares, oldest first. -/
def migrations : List Migration :=
  [migration0001, migration0002]

/-! ### The demo -/

/-- Whether `needle` occurs in `haystack`; the demo asserts that the generated source mentions the
constructors it should. -/
def occurs (haystack needle : String) : Bool :=
  (haystack.splitOn needle).length > 1

/-- The declared schema, changed the way a codebase changes: a column added to a table, an index
deleted, and a whole new table. `makemigrations` has to produce exactly those three steps. -/
def migSchemaNext : DatabaseRecipe where
  tables :=
    (migSchema.tables.map fun name t =>
      if name == "mig_book" then
        { t with columns := t.columns.insert "pages" { type := .int, nullable := true }
                 indexes := [] }
      else t).insert "mig_tag"
      { columns := .ofList
          [("label", { type := .varchar 50, nullable := false }),
           ("uses", { type := .int, nullable := false, default? := some (.int 0) })]
        primaryKey := ["label"] }

/--
Apply the migrations, check that the schema they fold to is the schema that resulted, show the
data, and plan the migration that the changed declaration would need.

Polymorphic in the monad, which is the whole point of declaring a migration rather than
introspecting a database: the same two migrations run on SQLite and on PostgreSQL.
-/
def migrationsDemo {m : Type → Type} [Monad m] [DBMonadWithMigrations m] [DBMonadTransactional m]
    [MonadLiftT IO m] (label : String) : m Unit := do
  IO.println s!"Declarative migrations ({label}):"
  let firstRun ← Db.Migration.migrate migrations 1700000000
  IO.println s!"  migrate applied: {firstRun}"
  let secondRun ← Db.Migration.migrate migrations 1700000001
  IO.println s!"  migrate again applied: {secondRun}"
  IO.println s!"  recorded: {← Db.Migration.applied (m := m)}"
  IO.println s!"  pending: {← Db.Migration.pending (m := m) migrations}"
  -- The schema the migrations fold to has to be the schema the database now has, or the fold is
  -- not a model of anything and `makemigrations` would diff against a fiction.
  let folded ← match Migration.foldAll migrations with
    | .ok recipe => pure recipe
    | .error e => DBMonadWithMigrations.abort e
  -- The database is shared with the other demos (and holds the tracking table), so the comparison
  -- is restricted to the tables these migrations own; everything else is somebody else's.
  let current ← DBMonadWithMigrations.currentDatabase
  let mine : DatabaseRecipe :=
    { tables := current.tables.filter fun name _ => folded.tables.contains name }
  IO.println <|
    s!"  column operations between the fold and the database: {(mine.operations folded).size}"
  IO.println s!"  constraint mismatches: {mine.constraintMismatches folded}"
  IO.println s!"  index operations: {(mine.declaredIndexOperations folded).size}"
  -- The declared schema agrees with the fold too, which is what "no changes detected" means.
  match planSteps migrations migSchema with
  | .ok [] => IO.println "  plan against the declared schema: no changes detected"
  | .ok steps => IO.println s!"  plan against the declared schema: {steps.length} step(s)"
  | .error e => IO.println s!"  plan against the declared schema failed: {e}"
  -- The data the `run` and `sql` steps put there.
  let books ← DBMonad.lookup
    (Query.orderBy [{ column := MigBookIndex.title }] (Query.all (d := migDb) MigDbIndex.book))
  IO.println "  books after the data migration:"
  for book in books do
    let year : Option Int := book.value MigBookIndex.year
    let note : Option String := book.value MigBookIndex.note
    IO.println s!"    {book.value MigBookIndex.title} ({repr year}) note={repr note}"
  -- The tracking table is not part of any declared schema, so `autoUpdate` has to leave it alone
  -- rather than drop it as a table nobody asked for. The target is the live schema itself, minus
  -- the tracking table, so that this changes nothing else: the database is shared with the others.
  DBMonadWithMigrations.autoUpdate (current.without Db.Migration.frameworkTables)
  IO.println <|
    s!"  db_migrations survives autoUpdate: " ++
    s!"{(← DBMonadWithMigrations.currentDatabase).tables.contains "db_migrations"}"
  -- What `makemigrations` would write for the changed declaration.
  match planSteps migrations migSchemaNext with
  | .error e => IO.println s!"  no plan: {e}"
  | .ok steps =>
    IO.println "  planned steps for the changed schema:"
    for step in steps do
      IO.println s!"    {step.describe}"
    let source := render "0003_pages_and_tags" steps
    IO.println "  generated source:"
    IO.println source
    IO.println <|
      s!"  mentions addColumn/createTable/dropIndex: " ++
      s!"{occurs source ".addColumn"}/{occurs source ".createTable"}/{occurs source ".dropIndex"}"

/-- The renames whose effect on the folded schema is the whole point of this demo: a column another
table's foreign key points at, a column an index is over, and the table itself. Both backends carry
the new name into the constraints, the index definitions and the foreign keys of every other table
when they perform the rename, so the schema the migrations fold to has to do the same. -/
def renameMigration : Migration where
  name := "0100_renames"
  steps :=
    [ .renameColumn "mig_book" "year" "published",
      .renameColumn "mig_author" "name" "fullName",
      .renameTable "mig_author" "mig_writer" ]

/-- Apply `renameMigration` on top of `base` and compare the fold with the database again.

Separate from `migrationsDemo` because the interesting number is the one after the renames: a fold
that renamed only the key of the column map would leave the primary key, the foreign key and the
index over the renamed column pointing at names that no longer exist, and the difference it then
reports is one no migration can close. -/
def renameDemo {m : Type → Type} [Monad m] [DBMonadWithMigrations m] [DBMonadTransactional m]
    [MonadLiftT IO m] (base : List Migration) : m Unit := do
  let all := base ++ [renameMigration]
  IO.println s!"  renames applied: {← Db.Migration.migrate all 1700000100}"
  let folded ← match Migration.foldAll all with
    | .ok recipe => pure recipe
    | .error e => DBMonadWithMigrations.abort e
  let current ← DBMonadWithMigrations.currentDatabase
  let mine : DatabaseRecipe :=
    { tables := current.tables.filter fun name _ => folded.tables.contains name }
  IO.println <|
    s!"  after the renames — column operations: {(mine.operations folded).size}, " ++
    s!"constraint mismatches: {mine.constraintMismatches folded}, " ++
    s!"index operations: {(mine.declaredIndexOperations folded).size}"

/-- Record a migration the code does not declare, which is the state `migrate` refuses to run in:
the database is then ahead of the code, and applying the rest on top of a history nobody has would
leave a schema no code describes. -/
def recordUnknownMigration {m : Type → Type} [Monad m] [DBMonadWithMigrations m] : m Unit :=
  DBMonadWithMigrations.rawExecute
    "INSERT INTO db_migrations (name, applied_at) VALUES ('9999_from_the_future', 0)"

/-- Undo `recordUnknownMigration`. -/
def forgetUnknownMigration {m : Type → Type} [Monad m] [DBMonadWithMigrations m] : m Unit :=
  DBMonadWithMigrations.rawExecute
    "DELETE FROM db_migrations WHERE name = '9999_from_the_future'"

end MigrationExample
