/-
Copyright (c) 2026 Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Merten
-/
import Db

/-!
# The declarative migration example

Two hand-written migrations and the demo that applies them. Backend-neutral on purpose: the point
of declaring a migration in Lean is that the same migration runs on either backend, so the demo is
polymorphic in the monad and both suites run the same one.

The tables are called `mig_author` and `mig_book` rather than `author` and `book` so that the demo
does not collide with the model tables the other examples `autoUpdate` into the same database.
-/

namespace MigrationExample

open Db.Migration

/-! ### The schema the migrations build

Written out as a `Table`, rather than generated by `@[model]`, because the point here is the
constraints: `mig_author` has a primary key for `mig_book`'s foreign key to reference. -/

inductive MigAuthorIndex where
  | name
  | age
  deriving DecidableEq, Hashable, Repr, Enum

instance : ToString MigAuthorIndex where
  toString
    | .name => "name"
    | .age => "age"

instance : FromString MigAuthorIndex where
  fromString
    | "name" => some .name
    | "age" => some .age
    | _ => none

instance : Indexing MigAuthorIndex where

def migAuthorTable : Table where
  Index := MigAuthorIndex
  columns
    | .name => { type := .varchar 100, nullable := false }
    | .age => { type := .int, nullable := false }
  primaryKey := [.name]

inductive MigBookIndex where
  | title
  | author
  | year
  | note
  deriving DecidableEq, Hashable, Repr, Enum

instance : ToString MigBookIndex where
  toString
    | .title => "title"
    | .author => "author"
    | .year => "year"
    | .note => "note"

instance : FromString MigBookIndex where
  fromString
    | "title" => some .title
    | "author" => some .author
    | "year" => some .year
    | "note" => some .note
    | _ => none

instance : Indexing MigBookIndex where

/-- `note` is the column the second migration adds, so the schema declared here is the schema
*after* both migrations. -/
def migBookTable : Table where
  Index := MigBookIndex
  columns
    | .title => { type := .varchar 200, nullable := false }
    | .author => { type := .varchar 100, nullable := false }
    | .year => { type := .int, nullable := true }
    | .note => { type := .text, nullable := true }
  primaryKey := [.title]
  foreignKeys :=
    [{ columns := [.author]
       foreignTable := "mig_author"
       foreignColumns := ["name"]
       onDelete := .cascade }]

inductive MigDbIndex where
  | author
  | book
  deriving DecidableEq, Hashable, Repr, Enum

instance : ToString MigDbIndex where
  toString
    | .author => "mig_author"
    | .book => "mig_book"

instance : FromString MigDbIndex where
  fromString
    | "mig_author" => some .author
    | "mig_book" => some .book
    | _ => none

instance : Indexing MigDbIndex where

def migDb : Database where
  Index := MigDbIndex
  tables
    | .author => migAuthorTable
    | .book => migBookTable

/-- The index the second migration leaves behind. -/
def yearIndex : TableIndex String :=
  { name := "idx_mig_book_year", keys := [{ column := "year", direction := .desc }] }

/-- The schema the code declares: the two tables and the one index. This is what
`makemigrations` diffs the migrations against. -/
def migSchema : DatabaseRecipe :=
  migDb.recipe.withIndexes "mig_book" [yearIndex]

/-! ### The migrations -/

/-- The first migration: the two tables as they were before `note` existed, and an index on the
column the books were looked up by at the time. -/
def migration0001 : Migration where
  name := "0001_initial"
  steps :=
    [ .createTable "mig_author"
        { columns := .ofList
            [("name", { type := .varchar 100, nullable := false }),
             ("age", { type := .int, nullable := false })]
          primaryKey := ["name"] },
      -- After `mig_author`: a `CREATE TABLE` carrying `REFERENCES` fails unless its target exists.
      .createTable "mig_book"
        { columns := .ofList
            [("title", { type := .varchar 200, nullable := false }),
             ("author", { type := .varchar 100, nullable := false }),
             ("year", { type := .int, nullable := true })]
          primaryKey := ["title"]
          foreignKeys :=
            [{ columns := ["author"], foreignTable := "mig_author",
               foreignColumns := ["name"], onDelete := .cascade }] },
      .createIndex "mig_book"
        { name := "idx_mig_book_author", keys := [{ column := "author" }] } ]

/-- The second migration: a new column, the rows that go in it, a fix-up in raw SQL, and the index
that replaces the one the first migration created.

The `run` step is the data migration: ordinary typed inserts, written once and running on either
backend. It comes after the `addColumn` because it inserts through `migDb`, which declares the
column the `addColumn` adds. -/
def migration0002 : Migration where
  name := "0002_data"
  steps :=
    [ .addColumn "mig_book" "note" { type := .text, nullable := true },
      .run do
        DBMonad.insert (d := migDb) (name := MigDbIndex.author)
          { value
              | .name => some (v"Ada")
              | .age => some (36 : Int) }
        DBMonad.insert (d := migDb) (name := MigDbIndex.author)
          { value
              | .name => some (v"Bram")
              | .age => some (50 : Int) }
        DBMonad.insert (d := migDb) (name := MigDbIndex.book)
          { value
              | .title => some (v"Persuasion")
              | .author => some (v"Ada")
              | .year => some (some (1817 : Int))
              | .note => none }
        DBMonad.insert (d := migDb) (name := MigDbIndex.book)
          { value
              | .title => some (v"Dracula")
              | .author => some (v"Bram")
              | .year => some (some (1897 : Int))
              | .note => none },
      -- The escape hatch: a data fix-up the operation language has no word for. The same text on
      -- both backends, so `Step.sql` rather than `Step.sqlByDialect`.
      .sql "UPDATE mig_book SET note = 'classic' WHERE year < 1850",
      .dropIndex "mig_book" "idx_mig_book_author",
      .createIndex "mig_book" yearIndex ]

/-- Every migration this example declares, oldest first. -/
def migrations : List Migration :=
  [migration0001, migration0002]

/-! ### The demo -/

/-- Whether `needle` occurs in `haystack`; the demo asserts that the generated source mentions the
constructors it should. -/
def occurs (haystack needle : String) : Bool :=
  (haystack.splitOn needle).length > 1

/-- The declared schema, changed the way a codebase changes: a column added to a table, an index
deleted, and a whole new table. `makemigrations` has to produce exactly those three steps. -/
def migSchemaNext : DatabaseRecipe where
  tables :=
    (migSchema.tables.map fun name t =>
      if name == "mig_book" then
        { t with columns := t.columns.insert "pages" { type := .int, nullable := true }
                 indexes := [] }
      else t).insert "mig_tag"
      { columns := .ofList
          [("label", { type := .varchar 50, nullable := false }),
           ("uses", { type := .int, nullable := false, default? := some (.int 0) })]
        primaryKey := ["label"] }

/--
Apply the migrations, check that the schema they fold to is the schema that resulted, show the
data, and plan the migration that the changed declaration would need.

Polymorphic in the monad, which is the whole point of declaring a migration rather than
introspecting a database: the same two migrations run on SQLite and on PostgreSQL.
-/
def migrationsDemo {m : Type → Type} [Monad m] [DBMonadWithMigrations m] [DBMonadTransactional m]
    [MonadLiftT IO m] (label : String) : m Unit := do
  IO.println s!"Declarative migrations ({label}):"
  -- Reading the record creates nothing: a database nothing has ever migrated has no tracking table
  -- and no applied migrations, and `applied` says the second without causing the first.
  IO.println <|
    s!"  before the first migrate — recorded: {← Db.Migration.applied (m := m)}, " ++
    s!"tracking table: " ++
    s!"{(← DBMonadWithMigrations.currentDatabase).tables.contains Db.Migration.trackingTableName}"
  -- And `migrate` creates it with one conditional statement rather than a check and a `CREATE
  -- TABLE`, which two concurrent runs would both pass and one of them then fail on.
  let createTracking :=
    Db.Migration.createTrackingTableStatement (DBMonadWithMigrations.dialect (m := m))
  IO.println <|
    s!"  the tracking table is created conditionally: " ++
    s!"{occurs createTracking "CREATE TABLE IF NOT EXISTS"}"
  let firstRun ← Db.Migration.migrate migrations 1700000000
  IO.println s!"  migrate applied: {firstRun}"
  let secondRun ← Db.Migration.migrate migrations 1700000001
  IO.println s!"  migrate again applied: {secondRun}"
  IO.println s!"  recorded: {← Db.Migration.applied (m := m)}"
  IO.println s!"  pending: {← Db.Migration.pending (m := m) migrations}"
  -- The schema the migrations fold to has to be the schema the database now has, or the fold is
  -- not a model of anything and `makemigrations` would diff against a fiction.
  let folded ← match Migration.foldAll migrations with
    | .ok recipe => pure recipe
    | .error e => DBMonadWithMigrations.abort e
  -- The database is shared with the other demos (and holds the tracking table), so the comparison
  -- is restricted to the tables these migrations own; everything else is somebody else's.
  let current ← DBMonadWithMigrations.currentDatabase
  let mine : DatabaseRecipe :=
    { tables := current.tables.filter fun name _ => folded.tables.contains name }
  IO.println <|
    s!"  column operations between the fold and the database: {(mine.operations folded).size}"
  IO.println s!"  constraint mismatches: {mine.constraintMismatches folded}"
  IO.println s!"  index operations: {(mine.declaredIndexOperations folded).size}"
  -- The declared schema agrees with the fold too, which is what "no changes detected" means.
  match planSteps migrations migSchema with
  | .ok [] => IO.println "  plan against the declared schema: no changes detected"
  | .ok steps => IO.println s!"  plan against the declared schema: {steps.length} step(s)"
  | .error e => IO.println s!"  plan against the declared schema failed: {e}"
  -- The data the `run` and `sql` steps put there.
  let books ← DBMonad.lookup
    (Query.orderBy [{ column := MigBookIndex.title }] (Query.all (d := migDb) MigDbIndex.book))
  IO.println "  books after the data migration:"
  for book in books do
    let year : Option Int := book.value MigBookIndex.year
    let note : Option String := book.value MigBookIndex.note
    IO.println s!"    {book.value MigBookIndex.title} ({repr year}) note={repr note}"
  -- The tracking table is not part of any declared schema, so `autoUpdate` has to leave it alone
  -- rather than drop it as a table nobody asked for. The target is the live schema itself, minus
  -- the tracking table, so that this changes nothing else: the database is shared with the others.
  DBMonadWithMigrations.autoUpdate (current.without Db.Migration.frameworkTables)
  IO.println <|
    s!"  db_migrations survives autoUpdate: " ++
    s!"{(← DBMonadWithMigrations.currentDatabase).tables.contains "db_migrations"}"
  -- What `makemigrations` would write for the changed declaration.
  match planSteps migrations migSchemaNext with
  | .error e => IO.println s!"  no plan: {e}"
  | .ok steps =>
    IO.println "  planned steps for the changed schema:"
    for step in steps do
      IO.println s!"    {step.describe}"
    let source := render "0003_pages_and_tags" steps
    IO.println "  generated source:"
    IO.println source
    IO.println <|
      s!"  mentions addColumn/createTable/dropIndex: " ++
      s!"{occurs source ".addColumn"}/{occurs source ".createTable"}/{occurs source ".dropIndex"}"

/-- The renames whose effect on the folded schema is the whole point of this demo: a column another
table's foreign key points at, a column an index is over, and the table itself. Both backends carry
the new name into the constraints, the index definitions and the foreign keys of every other table
when they perform the rename, so the schema the migrations fold to has to do the same. -/
def renameMigration : Migration where
  name := "0100_renames"
  steps :=
    [ .renameColumn "mig_book" "year" "published",
      .renameColumn "mig_author" "name" "fullName",
      .renameTable "mig_author" "mig_writer" ]

/-- Apply `renameMigration` on top of `base` and compare the fold with the database again.

Separate from `migrationsDemo` because the interesting number is the one after the renames: a fold
that renamed only the key of the column map would leave the primary key, the foreign key and the
index over the renamed column pointing at names that no longer exist, and the difference it then
reports is one no migration can close. -/
def renameDemo {m : Type → Type} [Monad m] [DBMonadWithMigrations m] [DBMonadTransactional m]
    [MonadLiftT IO m] (base : List Migration) : m Unit := do
  let all := base ++ [renameMigration]
  IO.println s!"  renames applied: {← Db.Migration.migrate all 1700000100}"
  let folded ← match Migration.foldAll all with
    | .ok recipe => pure recipe
    | .error e => DBMonadWithMigrations.abort e
  let current ← DBMonadWithMigrations.currentDatabase
  let mine : DatabaseRecipe :=
    { tables := current.tables.filter fun name _ => folded.tables.contains name }
  IO.println <|
    s!"  after the renames — column operations: {(mine.operations folded).size}, " ++
    s!"constraint mismatches: {mine.constraintMismatches folded}, " ++
    s!"index operations: {(mine.declaredIndexOperations folded).size}"

/-! ### Dropping an indexed column, and moving an index name

What a codebase does to a model after the renames: a field goes away, and an index is declared on
another table under a name that is already taken. Both are planned by `makemigrations` and then
applied, because the interesting question is not what the plan looks like but whether both backends
accept it. -/

/-- The schema the migrations fold to, or the fold's own complaint. -/
def foldOrAbort {m : Type → Type} [Monad m] [DBMonadWithMigrations m] (ms : List Migration) :
    m DatabaseRecipe :=
  match Migration.foldAll ms with
  | .ok recipe => pure recipe
  | .error e => DBMonadWithMigrations.abort e

/-- `current` restricted to the tables the migrations own; the database is shared with the other
demos, and the tracking table is nobody's declared schema. -/
def restrictedTo (current folded : DatabaseRecipe) : DatabaseRecipe :=
  { tables := current.tables.filter fun name _ => folded.tables.contains name }

/-- The declared schema after the model drops the field `published`, which the index
`idx_mig_book_year` is over. A declared schema that kept the index over a column it no longer has
would be one no database can be in, so the index goes with the field. -/
def withoutPublished (r : DatabaseRecipe) : DatabaseRecipe :=
  { tables := r.tables.map fun name t =>
      if name == "mig_book" then
        { t with
          columns := t.columns.erase "published"
          indexes := t.indexes.filter (fun idx => !idx.keys.any (·.column == "published")) }
      else t }

/-- An index on `mig_writer`, whose *name* the next declared schema moves to `mig_book`. -/
def sharedIndex : TableIndex String :=
  { name := "idx_mig_shared", keys := [{ column := "age" }] }

/-- The migration that creates it. Hand-written rather than planned: what is being tested is the
plan that moves it afterwards. -/
def sharedIndexMigration : Migration where
  name := "0201_shared_index"
  steps := [.createIndex "mig_writer" sharedIndex]

/-- The declared schema after the index name `idx_mig_shared` moves from `mig_writer` to
`mig_book`, over a column of its own.

An index name is unique across the whole database on both backends, so this is a drop and a create
that have to be emitted in that order. `mig_book` sorts before `mig_writer`, so a plan that ordered
the index operations table by table would emit the create first, and the backend would refuse it:
the name is still taken. -/
def movedSharedIndex (r : DatabaseRecipe) : DatabaseRecipe :=
  { tables := r.tables.map fun name t =>
      if name == "mig_writer" then
        { t with indexes := t.indexes.filter (·.name != sharedIndex.name) }
      else if name == "mig_book" then
        { t with indexes := t.indexes ++ [{ sharedIndex with keys := [{ column := "note" }] }] }
      else t }

/-- Drop a column an index is over, then move an index name to another table, planning both with
`makemigrations` and applying what it plans.

`base` is what `renameDemo` was given: this runs on the schema the renames left, so the column is
called `published` and the table `mig_writer`. -/
def dropColumnDemo {m : Type → Type} [Monad m] [DBMonadWithMigrations m] [DBMonadTransactional m]
    [MonadLiftT IO m] (base : List Migration) : m Unit := do
  let all := base ++ [renameMigration]
  let folded ← foldOrAbort all
  -- What the fold makes of a `dropColumn` on its own. An index over the column goes with it, the
  -- way PostgreSQL drops it; a constraint over it is refused, the way a constraint change always
  -- is here.
  match Step.apply folded (Step.dropColumn "mig_book" "published") with
  | .error e =>
    IO.println s!"  dropping the indexed column was refused, which it should not be: {e}"
  | .ok next =>
    letI left := ((next.tables["mig_book"]?.map (·.indexes)).getD []).map (·.name)
    IO.println s!"  in the fold, dropping `published` leaves mig_book with the indexes {left}"
  for column in ["title", "author"] do
    match Step.apply folded (Step.dropColumn "mig_book" column) with
    | .ok _ => IO.println s!"  dropping `{column}` was accepted, which it should not be"
    | .error e => IO.println s!"  {e}"
  -- The plan, and then the database.
  match planSteps all (withoutPublished folded) with
  | .error e => IO.println s!"  no plan for the drop: {e}"
  | .ok dropSteps =>
    IO.println "  planned steps for dropping the indexed column:"
    for step in dropSteps do
      IO.println s!"    {step.describe}"
    let withDrop := all ++ [{ name := "0200_drop_published", steps := dropSteps }]
    IO.println s!"  applied: {← Db.Migration.migrate withDrop 1700000200}"
    let withShared := withDrop ++ [sharedIndexMigration]
    IO.println s!"  the shared index created: {← Db.Migration.migrate withShared 1700000201}"
    let foldedShared ← foldOrAbort withShared
    match planSteps withShared (movedSharedIndex foldedShared) with
    | .error e => IO.println s!"  no plan for the move: {e}"
    | .ok moveSteps =>
      IO.println "  planned steps for moving the index name to another table:"
      for step in moveSteps do
        IO.println s!"    {step.describe}"
      let withMove := withShared ++ [{ name := "0202_move_index", steps := moveSteps }]
      IO.println s!"  applied: {← Db.Migration.migrate withMove 1700000202}"
      -- The database and the fold still agree, which is what makes the next plan trustworthy.
      let foldedFinal ← foldOrAbort withMove
      let mine := restrictedTo (← DBMonadWithMigrations.currentDatabase) foldedFinal
      IO.println <|
        s!"  after both — column operations: {(mine.operations foldedFinal).size}, " ++
        s!"constraint mismatches: {mine.constraintMismatches foldedFinal}, " ++
        s!"index operations: {(mine.declaredIndexOperations foldedFinal).size}"

/-- An atomic migration that gives up half way: its first step succeeds and its second does not.

The record of an atomic migration is written before its steps, so that a second `migrate` running
at the same time fails on the primary key of the tracking table rather than applying everything a
second time. This is what shows the record is nonetheless not left behind when the migration
fails: the transaction takes it back with the table the first step created. -/
def failingMigration : Migration where
  name := "0900_fails"
  steps :=
    [ .createTable "mig_never" { columns := .ofList [("x", { type := .int, nullable := true })] },
      .run (DBMonadWithMigrations.abort "this migration always gives up, on purpose") ]

/-- Record a migration the code does not declare, which is the state `migrate` refuses to run in:
the database is then ahead of the code, and applying the rest on top of a history nobody has would
leave a schema no code describes. -/
def recordUnknownMigration {m : Type → Type} [Monad m] [DBMonadWithMigrations m] : m Unit :=
  DBMonadWithMigrations.rawExecute
    "INSERT INTO db_migrations (name, applied_at) VALUES ('9999_from_the_future', 0)"

/-- Undo `recordUnknownMigration`. -/
def forgetUnknownMigration {m : Type → Type} [Monad m] [DBMonadWithMigrations m] : m Unit :=
  DBMonadWithMigrations.rawExecute
    "DELETE FROM db_migrations WHERE name = '9999_from_the_future'"

end MigrationExample
